### ISSUE TITLE
BCI Competition IV Dataset 2a

### ISSUE THREAD

**Issue by sagihaider** [YangWangsky/tf_EEGLearn#1]
Hi, 

I am wondering if you have tried your approach on BCI competition IV dataset 2A (http://www.bbci.de/competition/iv/#dataset2a). I am looking forward to implementing this. Any suggestion would be really helpful.

**Comment by YangWangsky** [comment]
Yes, I have tried, actually. First, I can't get the electrode location, it's not a standard 10-20 system. Second, frequency domain feature does not seem to be suitable for MI tasks.
