### ISSUE TITLE
"kernel" names

### ISSUE THREAD

**Issue by KarnBaca** [YangWangsky/tf_EEGLearn#11]
Hello, 

I have a question in the next line in train.py

l2_loss = tf.add_n([tf.nn.l2_loss(v) for v in Train_vars if 'kernel' in v.name])

I cannot find any layer with "kernel" in its name. Does that mean that the regularization is not applied? 

Thank you.

**Comment by YangWangsky** [comment]
The var's name depends on the version of TensorFlow. Maybe it should be "weight" in another version.
