### ISSUE TITLE
关于坐标点的问题

### ISSUE THREAD

**Issue by benpaodewoniu** [YangWangsky/tf_EEGLearn#4]
你好，我想请问原作者貌似没有提及哪个电极对应于哪个位置，那么如果我有自己的脑电信号想要生成对应的图像，那么我如何使用他的代码，进行对应电极生成图像？

**Comment by YangWangsky** [comment]
You need to get your own 3D EEG coordinates and match the coordinates to the EEG channel one by one, then organize your data as the style of Neuroscan_locs_orig.mat and FeatureMat_timeWin.mat in SampleData.
