### ISSUE TITLE
save Predictions

### ISSUE THREAD

**Issue by GulrukhTurabee** [YangWangsky/tf_EEGLearn#6]
Hello

I am trying to save predictions ( predicted values and true values) either as .mat file or .npy file. however, i can't find on the internet how can i saved in tensorflow? can you help me with that?

Thank You

**Comment by YangWangsky** [comment]
The variable pred in `summary, pred, av_test_err, av_test_acc = sess.run([test_summary_op, prediction, _loss, accuracy],`  could be directly operated by python, you can concat it with y_test and save as .csv, .mat or .npy.
