### ISSUE TITLE
Applying on EEG Motor Movement/Imagery Dataset 

### ISSUE THREAD

**Issue by javadbayazi** [YangWangsky/tf_EEGLearn#7]
I am trying to use the network to classify Motor Movement but this network works very well on the author's example data but doesn't work on new data.

Actually, I am using the "EEG Motor Movement/Imagery Dataset" (https://www.physionet.org/content/eegmmidb/1.0.0/) and it's a popular dataset, other people arrived at ~80 % accuracy and I got this accuracy with brain decode (CNN - https://tntlfreiburg.github.io/braindecode/). Now, I am trying to classify this data using EEGLearn (RNN-CNN https://github.com/YangWangsky/tf_EEGLearn) but I'm still on the chance level. Do you have any suggestions?

**Comment by YangWangsky** [comment]
The feature EEGLearn used here is PSD. It is a frequency domain feature, which I think is not suitable for MI. It seems something like CSP works well on MI. It means space information is better for MI. So, maybe you can try other features which work for MI
