### ISSUE TITLE
Unable to import?

### ISSUE THREAD

**Issue by dans-acc** [YangWangsky/tf_EEGLearn#9]
### Hello,

I get the following error message when importing the train module.

**Error message:**
File "/Users/dans/miniconda3/envs/basicmi-env/lib/python3.7/site-packages/EEGLearn/train.py", line 20, in <module>
    from utils import reformatInput, load_or_generate_images, iterate_minibatches
ModuleNotFoundError: No module named 'utils'

**Comment by YangWangsky** [comment]
Maybe you need to switch to the path where train.py exists, and then execute python
